source 'https://cdn.cocoapods.org'

platform :ios, '16.0'
use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

target 'iosApp' do
    pod 'composeApp', :path => '../composeApp'
    pod 'FirebaseAuth'
    pod 'GoogleSignIn'
end
